import type { Agent, Ticket } from './types';

export const mockAgents: Agent[] = [
  { id: 'agent-1', name: 'Alice Johnson', email: 'alice.j@kapture.cx', status: 'ONLINE', skillTags: ['Billing', 'Refunds', 'General Inquiry'], maxConcurrentTickets: 3, avatarUrl: 'https://placehold.co/100x100' },
  { id: 'agent-2', name: 'Bob Williams', email: 'bob.w@kapture.cx', status: 'ONLINE', skillTags: ['Technical Support', 'Hardware', 'Software'], maxConcurrentTickets: 5, avatarUrl: 'https://placehold.co/100x100' },
  { id: 'agent-3', name: 'Charlie Brown', email: 'charlie.b@kapture.cx', status: 'BUSY', skillTags: ['Billing', 'Technical Support', 'Enterprise'], maxConcurrentTickets: 4, avatarUrl: 'https://placehold.co/100x100' },
  { id: 'agent-4', name: 'Diana Miller', email: 'diana.m@kapture.cx', status: 'OFFLINE', skillTags: ['Refunds', 'Pre-Sales', 'Onboarding'], maxConcurrentTickets: 5, avatarUrl: 'https://placehold.co/100x100' },
  { id: 'agent-5', name: 'Ethan Davis', email: 'ethan.d@kapture.cx', status: 'ON_BREAK', skillTags: ['Technical Support', 'Mobile', 'iOS'], maxConcurrentTickets: 4, avatarUrl: 'https://placehold.co/100x100' },
  { id: 'agent-6', name: 'Fiona Garcia', email: 'fiona.g@kapture.cx', status: 'ONLINE', skillTags: ['Pre-Sales', 'Enterprise', 'Demos'], maxConcurrentTickets: 2, avatarUrl: 'https://placehold.co/100x100' },
  { id: 'agent-7', name: 'George Rodriguez', email: 'george.r@kapture.cx', status: 'BUSY', skillTags: ['Hardware', 'Repairs', 'Logistics'], maxConcurrentTickets: 3, avatarUrl: 'https://placehold.co/100x100' },
  { id: 'agent-8', name: 'Hannah Wilson', email: 'hannah.w@kapture.cx', status: 'ONLINE', skillTags: ['Billing', 'Account Management', 'Renewals'], maxConcurrentTickets: 5, avatarUrl: 'https://placehold.co/100x100' },
  { id: 'agent-9', name: 'Ian Martinez', email: 'ian.m@kapture.cx', status: 'OFFLINE', skillTags: ['Technical Support', 'Android', 'Mobile'], maxConcurrentTickets: 5, avatarUrl: 'https://placehold.co/100x100' },
  { id: 'agent-10', name: 'Jane Anderson', email: 'jane.a@kapture.cx', status: 'ONLINE', skillTags: ['Onboarding', 'General Inquiry', 'User Training'], maxConcurrentTickets: 3, avatarUrl: 'https://placehold.co/100x100' },
];

export const mockTickets: Ticket[] = [
  { id: 'TKT-001', title: 'Cannot access my account', description: 'I am unable to log in to my account. It says invalid credentials but I am sure they are correct.', priority: 'HIGH', channel: 'EMAIL', status: 'ASSIGNED', agentId: 'agent-2', createdAt: new Date('2023-10-26T10:00:00Z'), updatedAt: new Date('2023-10-26T10:05:00Z') },
  { id: 'TKT-002', title: 'Question about billing', description: 'I have a question regarding my last invoice. There seems to be an extra charge.', priority: 'MEDIUM', channel: 'CHAT', status: 'ASSIGNED', agentId: 'agent-1', createdAt: new Date('2023-10-26T11:20:00Z'), updatedAt: new Date('2023-10-26T11:22:00Z') },
  { id: 'TKT-003', title: 'Product is not working', description: 'The product I bought last week stopped working. I need technical assistance.', priority: 'URGENT', channel: 'PHONE', status: 'OPEN', createdAt: new Date('2023-10-27T09:00:00Z'), updatedAt: new Date('2023-10-27T09:00:00Z') },
  { id: 'TKT-004', title: 'Pre-sales inquiry', description: 'I want to know more about your enterprise plan features.', priority: 'LOW', channel: 'WEB_FORM', status: 'PENDING_AGENT_REPLY', agentId: 'agent-6', createdAt: new Date('2023-10-27T14:30:00Z'), updatedAt: new Date('2023-10-27T14:30:00Z') },
  { id: 'TKT-005', title: 'Refund request for order #5829', description: 'I would like to request a refund for my recent order.', priority: 'MEDIUM', channel: 'EMAIL', status: 'RESOLVED', agentId: 'agent-4', createdAt: new Date('2023-10-25T15:00:00Z'), updatedAt: new Date('2023-10-25T18:30:00Z') },
  { id: 'TKT-006', title: 'Password Reset', description: 'I forgot my password and the reset link is not working.', priority: 'HIGH', channel: 'WHATSAPP', status: 'OPEN', createdAt: new Date('2023-10-28T08:00:00Z'), updatedAt: new Date('2023-10-28T08:00:00Z') },
  { id: 'TKT-007', title: 'Feature Request: Dark Mode', description: 'Please add a dark mode to the application. It would be easier on the eyes.', priority: 'LOW', channel: 'WEB_FORM', status: 'CLOSED', agentId: 'agent-3', createdAt: new Date('2023-10-24T12:00:00Z'), updatedAt: new Date('2023-10-25T10:00:00Z') },
  { id: 'TKT-008', title: 'Mobile app crashing on startup (iOS)', description: 'The iOS app crashes immediately after I open it. I am on the latest version of the app and iOS.', priority: 'URGENT', channel: 'CHAT', status: 'ESCALATED', agentId: 'agent-5', createdAt: new Date('2023-10-28T10:00:00Z'), updatedAt: new Date('2023-10-28T10:15:00Z') },
  { id: 'TKT-009', title: 'How to set up enterprise SSO?', description: 'We need help configuring SSO for our enterprise account. Can someone guide us?', priority: 'HIGH', channel: 'EMAIL', status: 'PENDING_CUSTOMER_REPLY', agentId: 'agent-3', createdAt: new Date('2023-10-27T18:00:00Z'), updatedAt: new Date('2023-10-28T09:00:00Z') },
  { id: 'TKT-010', title: 'Hardware repair status?', description: 'I sent my device for repair last week, what is the status? RMA #12345', priority: 'MEDIUM', channel: 'PHONE', status: 'ON_HOLD', agentId: 'agent-7', createdAt: new Date('2023-10-28T11:00:00Z'), updatedAt: new Date('2023-10-28T11:05:00Z') },
  { id: 'TKT-011', title: 'Account renewal query', description: 'Our account is up for renewal next month. Can we get a quote for 50 additional seats?', priority: 'MEDIUM', channel: 'EMAIL', status: 'ASSIGNED', agentId: 'agent-8', createdAt: new Date('2023-10-28T12:00:00Z'), updatedAt: new Date('2023-10-28T12:00:00Z') },
  { id: 'TKT-012', title: 'New user training session needed', description: 'We have 10 new team members who need to be trained on using the platform.', priority: 'LOW', channel: 'WEB_FORM', status: 'OPEN', createdAt: new Date('2023-10-28T14:00:00Z'), updatedAt: new Date('2023-10-28T14:00:00Z') },
];
